### PR TITLE
Rootstock modules

### PR DESCRIPTION
**Pull request by Oskal174**
Added Main, Trace, ERC20, ERC721, ERC1155 modules for Rootstock blockchain.

### CODE REVIEW

**Comment by Har01d** [comment]
Please don't forget to test the mempool. Without 9161dde, `php 3xpl.php rootstock-main B -1 E` was returning the following:
```2023-10-13 19:54:07.766030       *ERROR         Got level 2 error: Undefined array key "hash" in /var/oss/Modules/Common/EVMMainModule.php at line 288, st: [x]```

**Comment by Har01d** [comment]
The database has been fully populated with data: https://3xpl.com/rootstock

**Review by Har01d — APPROVED** [review]

**Review by alexqrid — APPROVED** [review]
[Removed](https://github.com/3xplcom/Core/pull/52/commits/fd00db179dbdcaf198ee4a5230554afd1a8f8bfa) `rsk_trace` function as it was used for `debug_traceBlock` parsing and is not needed with parity tracers.

**Comment by Har01d** [comment]
Merging, thanks!

**Pull request merged**
